### ISSUE TITLE
Phone no responsed。

### ISSUE THREAD

**Issue by geminird** [mirsamantajbakhsh/LiveHiddenCamera#1]
I test，system no responsed，need reboot 。

**Comment by mirsamantajbakhsh** [comment]
Phone works but because there is a hidden layer (over main layer for receiving the preview frames), click does not respond. I mean when you click anywhere, the phone will no respond. You should kill the process by adb.

```
adb shell
ps  // Find the process id (pid) of your application
kill pid // (as super user)
```

or you can stop the application by calling:
```adb shell am force-stop com.my.app.package```

Check **TODO** section. _Cloak and Dagger_  can be used to overcome this problem.

**Comment by geminird** [comment]
cloak and dagger is too complicated to me,  if i want live audio only, can be not use the over hidden layer?  how to do.  thanks!

**Comment by mirsamantajbakhsh** [comment]
It is possible. These links from [IceCast](https://icecast.org/apps/) can be used:

http://novastreamapps.blogspot.com/

https://coolmic.net/

I will work on another library for live audio stream. I'll try to publish it during a month.

**Comment by mirsamantajbakhsh** [comment]
@geminird I've created a live audio library from CoolMic. The source and AAR are available with a demo video. Checkout:

https://mstajbakhsh.ir/broadcast-yourself-through-android/

https://github.com/mirsamantajbakhsh/LiveRadio

https://youtu.be/ujgRlYc9rMg
